import ms from "ms.macro"

const SupportedChainId =  {
    MAINNET: 1,
    ROPSTEN : 3,
    RINKEBY : 4,
    GOERLI : 5,
    KOVAN : 42,
  
    ARBITRUM_ONE : 42161,
    ARBITRUM_RINKEBY : 421611,
    OPTIMISM : 10,
    OPTIMISTIC_KOVAN : 69,
}

export const CHAIN_INFO = {
    [SupportedChainId.ARBITRUM_ONE]: {
      blockWaitMsBeforeWarning: ms`10m`,
      bridge: 'https://bridge.arbitrum.io/',
      docs: 'https://offchainlabs.com/',
      explorer: 'https://arbiscan.io/',
      infoLink: 'https://info.uniswap.org/#/arbitrum',
      label: 'Arbitrum',
      nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
      rpcUrls: ['https://arb1.arbitrum.io/rpc'],
    },
    [SupportedChainId.ARBITRUM_RINKEBY]: {
      blockWaitMsBeforeWarning: ms`10m`,
      bridge: 'https://bridge.arbitrum.io/',
      docs: 'https://offchainlabs.com/',
      explorer: 'https://rinkeby-explorer.arbitrum.io/',
      infoLink: 'https://info.uniswap.org/#/arbitrum/',
      label: 'Arbitrum Rinkeby',
      nativeCurrency: { name: 'Rinkeby ArbETH', symbol: 'rinkArbETH', decimals: 18 },
      rpcUrls: ['https://rinkeby.arbitrum.io/rpc'],
    },
    [SupportedChainId.MAINNET]: {
      docs: 'https://docs.uniswap.org/',
      explorer: 'https://etherscan.io/',
      infoLink: 'https://info.uniswap.org/#/',
      label: 'Ethereum',
      nativeCurrency: { name: 'ETH', symbol: 'ETH', decimals: 18 },
    },
    [SupportedChainId.RINKEBY]: {
      docs: 'https://docs.uniswap.org/',
      explorer: 'https://rinkeby.etherscan.io/',
      infoLink: 'https://info.uniswap.org/#/',
      label: 'Rinkeby',
      nativeCurrency: { name: 'Rinkeby ETH', symbol: 'rinkETH', decimals: 18 },
    },
    [SupportedChainId.ROPSTEN]: {
      docs: 'https://docs.uniswap.org/',
      explorer: 'https://ropsten.etherscan.io/',
      infoLink: 'https://info.uniswap.org/#/',
      label: 'Ropsten',
      nativeCurrency: { name: 'Ropsten ETH', symbol: 'ropETH', decimals: 18 },
    },
    [SupportedChainId.KOVAN]: {
      docs: 'https://docs.uniswap.org/',
      explorer: 'https://kovan.etherscan.io/',
      infoLink: 'https://info.uniswap.org/#/',
      label: 'Kovan',
      nativeCurrency: { name: 'Kovan ETH', symbol: 'kovETH', decimals: 18 },
    },
    [SupportedChainId.GOERLI]: {
      docs: 'https://docs.uniswap.org/',
      explorer: 'https://goerli.etherscan.io/',
      infoLink: 'https://info.uniswap.org/#/',
      label: 'Görli',
      nativeCurrency: { name: 'Görli ETH', symbol: 'görETH', decimals: 18 },
    },
    [SupportedChainId.OPTIMISM]: {
      blockWaitMsBeforeWarning: ms`10m`,
      bridge: 'https://gateway.optimism.io/',
      docs: 'https://optimism.io/',
      explorer: 'https://optimistic.etherscan.io/',
      infoLink: 'https://info.uniswap.org/#/optimism',
      label: 'OΞ',
      nativeCurrency: { name: 'Optimistic ETH', symbol: 'ETH', decimals: 18 },
      rpcUrls: ['https://mainnet.optimism.io'],
      statusPage: 'https://optimism.io/status',
    },
    [SupportedChainId.OPTIMISTIC_KOVAN]: {
      blockWaitMsBeforeWarning: ms`10m`,
      bridge: 'https://gateway.optimism.io/',
      docs: 'https://optimism.io/',
      explorer: 'https://optimistic.etherscan.io/',
      infoLink: 'https://info.uniswap.org/#/optimism',
      label: 'Optimistic Kovan',
      rpcUrls: ['https://kovan.optimism.io'],
      nativeCurrency: { name: 'Optimistic kovETH', symbol: 'kovOpETH', decimals: 18 },
      statusPage: 'https://optimism.io/status',
    },
  }